[tool.poetry]
name = "predictor"
version = "0.1.0"
description = ""
authors = ["robert-clayton <41345902+robert-clayton@users.noreply.github.com>"]

[tool.poetry.dependencies]
python = "^3.9"
torch = "^1.9.0"
torchtext = "^0.10.0"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
