[tool.poetry]
name = "watcher"
version = "0.1.0"
description = ""
authors = ["robert-clayton <41345902+robert-clayton@users.noreply.github.com>"]

[tool.poetry.dependencies]
python = "^3.9"
cryptowatch-sdk = "^0.0.14"
python-dotenv = "^0.19.0"
pandas = "^1.3.1"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
