name: Checks - Watcher (CI)

on:
  push:
    branches: [develop, master]
    paths:    [packages/watcher/src/**]
  pull_request:
    types:    [edited, assigned, opened, synchronize, reopened]
    paths:    [packages/watcher/src/**]
  workflow_dispatch:

defaults:
  run:
    shell: bash

jobs:
  nox:
    name: Nox Checks
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v1
        with:
          python-version: 3.9.6
      - uses: excitedleigh/setup-nox@v2.0.0
      - uses: Gr1N/setup-poetry@v7
        with:
          path: ~/.cache/pypoetry/virtualenvs
          key: ${{ runner.os }}-poetry-${{ hashFiles('poetry.lock') }}
      - run: cd packages/watcher && nox
  dispatch:
    name:     Dispatch Build
    runs-on:  ubuntu-latest
    needs:    [nox]
    steps:
      - uses: actions/checkout@v2
      - run: |
          CURRENT_BRANCH=${${{ github.ref }}#refs/heads/}
          @echo "CURRENT_BRANCH=$CURRENT_BRANCH" >> $GITHUB_ENV
      - uses: peter-evans/repository-dispatch@v1
        with:
          token:      ${{ github.token }}
          repository: ${{ github.repository }}
          event-type: 'build'
          client-payload: '{"type": "build", "branch": "${{ env.CURRENT_BRANCH }}"}'
