name: PR Repo Labeler

on:
  pull_request:
    types: [opened]
    branches:
      - main

jobs:
  label_pr:
    name: Label PR With Repo(s)
    runs-on: ubuntu-latest
    steps:
      - name: Label PRs
        uses: adamzolyak/monorepo-pr-labeler-action@patching
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BASE_DIRS:    'packages'